### ISSUE TITLE
Setup.py fails

### ISSUE THREAD

**Issue by RiccardoBuscicchio** [andrewcron/dpmix#4]
`setup.py` fails both within a python 3.6 and a python 2.7 environment.
Requirements satisfied except:
* PyCUDA
* scikits.cuda
which I think are optional. 
```
running install
running build
running build_py
running build_ext
skipping 'src/munkres.cpp' Cython extension (up-to-date)
cythoning src/sampler_utils.pyx to src/sampler_utils.cpp
/home/riccardo/anaconda3/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/riccardo/Desktop/dpmix/src/sampler_utils.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
    cdef bool solve(vec x, mat A, vec b)
    cdef vec solve(mat A, vec b)
    cdef bool solve(mat X, mat A, mat B)
    cdef mat solve(mat A, mat B)
    cdef bool eig_sym(vec eigval, mat eigvec, mat B)
    cdef bool svd(mat U, vec s, mat V, mat X, method = "standard")
                ^
------------------------------------------------------------

/home/riccardo/anaconda3/lib/python3.6/site-packages/cyarma/cyarma.pyx:103:17: Extern functions cannot have default arguments values.

Error compiling Cython file:
------------------------------------------------------------
...
                           double gamma, vec * pr_mu, double pr_nu, mat * pr_phi,
                           vec * hdp_rngs, do_parallel=True, hdp=False):
    cdef bool is_hdp
    cdef int k, nthd, chunk, i, J, cnt
    cdef unsigned long Seed = np.random.randint(2**32)
    cdef rng_sampler[double] * R = new rng_sampler[double](Seed)
                                                          ^
------------------------------------------------------------

src/sampler_utils.pyx:209:59: Cannot assign type 'unsigned long' to 'mt19937'

Error compiling Cython file:
------------------------------------------------------------
...
                np.ndarray[np.double_t, ndim=1] AR,
                np.ndarray[np.double_t, ndim=1] prop_scale,
                do_parallel = False):

    cdef unsigned long Seed = np.random.randint(2**32)
    cdef rng_sampler[double] * R = new rng_sampler[double](Seed)
                                                          ^
------------------------------------------------------------

src/sampler_utils.pyx:398:59: Cannot assign type 'unsigned long' to 'mt19937'

Error compiling Cython file:
------------------------------------------------------------
...
                  double e0, double f0,
                  np.ndarray[np.double_t, ndim=1] prop_scale,
                  np.ndarray[np.double_t, ndim=1] AR):
    # just reuse with dummy vars for beta things
    cdef unsigned long Seed = np.random.randint(2**32)
    cdef rng_sampler[double] * R = new rng_sampler[double](Seed)
                                                          ^
------------------------------------------------------------

src/sampler_utils.pyx:479:59: Cannot assign type 'unsigned long' to 'mt19937'
building 'dpmix.sampler' extension
gcc -pthread -B /home/riccardo/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/riccardo/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/riccardo/anaconda3/lib/python3.6/site-packages/cyarma -I/home/riccardo/anaconda3/lib/python3.6/site-packages/cyrand -I/usr/include -I/usr/local/include -I/opt/local/include -I/home/riccardo/anaconda3/include/python3.6m -c src/sampler_utils.cpp -o build/temp.linux-x86_64-3.6/src/sampler_utils.o -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/sampler_utils.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^~~~~
error: command 'gcc' failed with exit status 1
```
Is this project discontinued? Has it been moved somewhere else?

**Comment by whitews** [comment]
Hi,

I maintain an updated fork of this code here:

https://github.com/whitews/dpmix

It should work on both Python 2 and 3.

**Comment by RiccardoBuscicchio** [comment]
> Hi,
> 
> I maintain an updated fork of this code here:
> 
> https://github.com/whitews/dpmix
> 
> It should work on both Python 2 and 3.

I have the same issue on your fork as well. Are there other checks I can do to help you fix this?

**Comment by whitews** [comment]
Riccardo, can you provide the versions of Cython and gcc you are using?

**Comment by RiccardoBuscicchio** [comment]
> Riccardo, can you provide the versions of Cython and gcc you are using?

python 3.6.6
cython 0.29
gcc 7.2.0

**Comment by whitews** [comment]
Hmm, I am using roughly the same (Py 3.6.7, Cython 0.29, gcc 7.3.0) and cannot replicate the error. 

Are you using Linux, and if so, a Debian based distro? Did you install cyrand and cyarma? Also, the libarmadillo headers are required as well.

** Edit **
It may also be related to the libboost version, which version do you have installed?

**Comment by RiccardoBuscicchio** [comment]
I'm on Ubuntu 17.10 
libboost-all-dev package is `Version: 1.62.0.1`
libarmadillo-dev package is `Version: 1:7.960.1+dfsg-1`
cyrand and cyarma python package are installed.

**Comment by whitews** [comment]
Ok, thanks. I've tested on a 16.04 VM I have and on 18.04 and 18.10, all install ok. I'll setup a fresh 17.10 VM and see if I can reproduce this.

**Comment by RiccardoBuscicchio** [comment]
For your information, I get exactly the same error with another machine (OS freshly installed):

Ubuntu 18.10
Python 3.6.7
gcc 8.2.0
`libboost-all-dev` package is `Version: 1.67.0`
`libarmadillo-dev` package is `Version: 1:9.100.5+dfsg-1`

**Comment by whitews** [comment]
Ok, that helps. Using a fresh 18.10 install, it builds for me. Note, I am not using libboost-all-dev, just libboost1.67-dev. Also installed build-essential.

**Comment by RiccardoBuscicchio** [comment]
build-essential is in both. 
Nothing changes with `libboost1.62-dev` and `libboost1.66-dev` installed respectively.

**Comment by whitews** [comment]
Not sure then what is different in our setups. Are you using a virtualenv or anything else you can think of that might be different? My last test with 18.10 was with a fresh install using only apt installs other than the git based dependencies.

**Comment by RiccardoBuscicchio** [comment]
I'm not in a virtual environment. I will try soon with a live image of 18.10 and I'll let you know.
Just to make sure, is this the setup I should try:
APTs:
```
build-essential
libboost1.6x-dev
libarmadillo-dev
```
pip3
```
numpy
scipy
cython
cyarma
cyrand
gpustats
mpi4py
```
git repo
```
dpmix
```

?

**Comment by whitews** [comment]
Ahh, I think the issue is with cyrand, you should install cyrand and cyarma via git as well:

```
git clone https://github.com/andrewcron/cyrand
git clone https://github.com/andrewcron/cy_armadillo
```

See if that does the trick.

Also, for my fork mpi4py is no longer needed.

**Comment by RiccardoBuscicchio** [comment]
It works, indeed.
